Switch to yaml folded style string to avoid confusing escape characters

diff --git a/infra/local/docker-compose.yml b/infra/local/docker-compose.yml
--- a/infra/local/docker-compose.yml
+++ b/infra/local/docker-compose.yml
@@ -152,16 +152,16 @@ services:
         condition: service_healthy
     image: quay.io/minio/mc:RELEASE.2025-05-21T01-59-54Z
     env_file: *env-file
-    entrypoint: |
+    entrypoint: >
       /bin/sh -c "
-      /usr/bin/mc alias set minio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} \
-      if ! /usr/bin/mc ls minio/$${MINIO_BUCKET_NAME}; then \
-        echo \"Bucket '$${MINIO_BUCKET_NAME}' not found, creating...\" \
-        /usr/bin/mc mb minio/$${MINIO_BUCKET_NAME}; \
-        echo \"Bucket '$${MINIO_BUCKET_NAME}' created.\" \
-      else \
-        echo \"Found bucket '$${MINIO_BUCKET_NAME}'\" \
-      fi \
+      /usr/bin/mc alias set minio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
+      if ! /usr/bin/mc ls minio/$${MINIO_BUCKET_NAME}; then
+        echo \"Bucket '$${MINIO_BUCKET_NAME}' not found, creating...\"
+        /usr/bin/mc mb minio/$${MINIO_BUCKET_NAME};
+        echo \"Bucket '$${MINIO_BUCKET_NAME}' created.\"
+      else
+        echo \"Found bucket '$${MINIO_BUCKET_NAME}'\"
+      fi
       "
     networks: *local-networks
 
